**Array**
1. It is a group of homogenous data (similar data)
2. It can be multidimensional
3. It is preferred over list or tuple in case of doing mathematical operation
4. Numpy (Numerical Python) - It is a library/package that can be used to work on mutlidimensional arrays and apply different mathematical operations


In [1]:
import numpy as np

In [ ]:
a1 = [10,20,30]
a2= [ 1,2,3]
print(a1 + a2) #addition on lists = add strings
print(a1 * 3)  #repeat thrice

[10, 20, 30, 1, 2, 3]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [ ]:
sum = []
for i in range (len(a1)):
  sum.append(a1[i]+a2[i])
print(sum)

[11, 22, 33]


In [ ]:
a3 = np.array([10,20,30])
a4 = np.array([1,2,3])
print(a3 + a4)  #addition
print(a3 * 3)   #multiplication

[11 22 33]
[30 60 90]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([[1,2,3,4,5,6,7,8,9,10]])
c = np.array([[1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10]])
d = np.array([[[1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10]]])
e = np.array([[[1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10]],
              [[1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10],
              [1,2,3,4,5,6,7,8,9,10]]])

In [ ]:
### Number of elements 
print(len(a))
print(len(b))
print(len(c))
print(len(d))
print(len(e))


10
1
4
1
2


In [ ]:
### Dimension of array
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

1
2
2
3
3


In [ ]:
### Shape of array
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

(10,)
(1, 10)
(4, 10)
(1, 4, 10)
(2, 4, 10)


In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)
print(e.dtype)

int64
int64
int64
int64
int64


In [ ]:
f = np.array([10,20,30.5,89.7])
print(f.dtype)
print(f)
g = np.array([10,20,30.5,89.7,"Umang"])
print(g.dtype)
print(g)

float64
[10.  20.  30.5 89.7]
<U32
['10' '20' '30.5' '89.7' 'Umang']


In [ ]:
### Random Numbers
np.random.randint(10)

0

In [ ]:
np.random.seed(130)
np.random.randint(100,500)

217

In [ ]:
np.random.randint(100,500,10)

In [ ]:
np.random.randint(100,500,(5,4))

In [ ]:
np.random.randint(100,500,(5,4,3))

In [ ]:
np.random.uniform(100,500,10)

array([112.64751839, 424.13548088, 120.59872958, 328.48712123,
       235.77622603, 187.13058877, 405.6652642 , 479.10302034,
       382.44092606, 472.65861023])

In [ ]:
np.round(np.random.uniform(100,500,10),2)

array([275.55, 350.77, 366.92, 131.38, 126.81, 293.36, 454.1 , 420.47,
       396.43, 193.04])

In [ ]:
### Slicing of array

np.random.seed(1)
data = np.random.randint(100,500,(7,8))
print(data)

[[137 335 496 172 355 493 303 233]
 [435 244 229 171 337 490 381 278]
 [376 354 457 495 352 256 498 150]
 [168 315 341 452 186 241 493 107]
 [419 417 122 413 101 484 416 309]
 [364 316 241 215 221 130 171 487]
 [149 413 103 380 143 176 126 408]]


In [ ]:
data[:,:]

array([[137, 335, 496, 172, 355, 493, 303, 233],
       [435, 244, 229, 171, 337, 490, 381, 278],
       [376, 354, 457, 495, 352, 256, 498, 150],
       [168, 315, 341, 452, 186, 241, 493, 107],
       [419, 417, 122, 413, 101, 484, 416, 309],
       [364, 316, 241, 215, 221, 130, 171, 487],
       [149, 413, 103, 380, 143, 176, 126, 408]])

In [ ]:
data[1,3]

171

In [ ]:
### Change the datatype of element of an array
x = np.random.randint(100,500,10)
x


array([491, 382, 253, 204, 122, 365, 295, 226, 379, 481])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y = x.astype('float')
y

array([491., 382., 253., 204., 122., 365., 295., 226., 379., 481.])

In [ ]:
y = x.astype('str')
y

In [ ]:
np.random.seed(1)
data = np.random.randint(100,500,(5,6))
print(data)

[[137 335 496 172 355 493]
 [303 233 435 244 229 171]
 [337 490 381 278 376 354]
 [457 495 352 256 498 150]
 [168 315 341 452 186 241]]


In [ ]:
print(data.min())
print(data.min(axis=0))   ## column wise
print(data.min(axis=1))   ## row wise

In [ ]:
print(data.max())
print(data.max(axis=0))   ## column wise
print(data.max(axis=1))   ## row wise

498
[457 495 496 452 498 493]
[496 435 490 498 452]


In [ ]:
print(data.sum())
print(data.sum(axis=0))   ## column wise
print(data.sum(axis=1))   ## row wise

9730
[1402 1868 2005 1402 1644 1409]
[1988 1615 2216 2208 1703]


In [ ]:
print(data.mean())
print(data.mean(axis=0))   ## column wise
print(data.mean(axis=1))   ## row wise

324.3333333333333
[280.4 373.6 401.  280.4 328.8 281.8]
[331.33333333 269.16666667 369.33333333 368.         283.83333333]


In [ ]:
print(data.argmax())
print(data.argmax(axis=0))   ## column wise
print(data.argmax(axis=1))   ## row wise

22
[3 3 0 4 3 0]
[2 2 1 4 3]


In [ ]:
print(data.argmin())
print(data.argmin(axis=0))   ## column wise
print(data.argmin(axis=1))   ## row wise

0
[0 1 4 0 4 3]
[0 5 3 5 0]


In [ ]:
### Change the shape and dimension of array

In [ ]:
data.shape

(5, 6)

In [ ]:
data

array([[137, 335, 496, 172, 355, 493],
       [303, 233, 435, 244, 229, 171],
       [337, 490, 381, 278, 376, 354],
       [457, 495, 352, 256, 498, 150],
       [168, 315, 341, 452, 186, 241]])

In [ ]:
data_1 = data.reshape(30)
data_2 = data.reshape((2,15))     ## (6,5),(10,3),(3,10),(1,30),(30,1),(2,15),(15,2)
data_3 = data.reshape((2,5,3))

In [ ]:
data_1

array([137, 335, 496, 172, 355, 493, 303, 233, 435, 244, 229, 171, 337,
       490, 381, 278, 376, 354, 457, 495, 352, 256, 498, 150, 168, 315,
       341, 452, 186, 241])

In [ ]:
data_2

array([[137, 335, 496, 172, 355, 493, 303, 233, 435, 244, 229, 171, 337,
        490, 381],
       [278, 376, 354, 457, 495, 352, 256, 498, 150, 168, 315, 341, 452,
        186, 241]])

In [ ]:
data_3

array([[[137, 335, 496],
        [172, 355, 493],
        [303, 233, 435],
        [244, 229, 171],
        [337, 490, 381]],

       [[278, 376, 354],
        [457, 495, 352],
        [256, 498, 150],
        [168, 315, 341],
        [452, 186, 241]]])